### ISSUE TITLE
Kraken Order Example 1 - "NameError: name 'ticker' is not defined"

### ISSUE THREAD

**Issue by aengusrooneygrafana** [IgorWounds/Kraken-API---A-Complete-Guide-Algotrading101#1]
Hi Igor, 

Great article - very helpful thanks!  I'm trying out ```Kraken Order Example 1.ipynb```  but hitting an error..  I'm checking the docs but I can't see the issue, is there anything you can suggest here please?  

https://docs.kraken.com/rest/#operation/getTickerInformation 

```
$ ./execute_order_on_price.py
Error obtaining BTC data
Traceback (most recent call last):
  File "./execute_order_on_price.py", line 29, in <module>
    if float(ticker.a[0][0]) >= 60000.00:
NameError: name 'ticker' is not defined
 ```

**Comment by IgorWounds** [comment]
Hey,
There was a typo where I wrote "ticker" instead of the btc_data variable. Will update it now.

**Comment by IgorWounds** [comment]
If you get more troubles with their lower-level API please check out how to do an order with their higher-level API which you can find on my GitHub Kraken Course / Chapter 3 repo
